#!/usr/bin/python

distinct_terms = {}

for i in range(2,101):
    for j in range(2,101):
        power = i**j
        distinct_terms[power] = power

print "The number of distinct terms in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100 is: " + str(len(distinct_terms))


